### ISSUE TITLE
Lower API cost

### ISSUE THREAD

**Issue by mailtokamalnayan** [priyanshunayan/movie-finder-api#1]
Hitting an API this frequently doesn't seem like the best way. I hope I am wrong but if we can find a better strategy to check if the user has joined, it would be great.

![image](https://user-images.githubusercontent.com/2495633/121090819-67efac80-c7e9-11eb-8c38-21861d8a5d41.png)

**Comment by priyanshunayan** [comment]
Yeah totally. Shifted to Web sockets.
